export const template = (text, requires = []) => ({ text, requires });

export const newsTemplates = {
  victory: {
    narrow: {
      labels: [
        'POR LA MÍNIMA', '¡JUSTITO!', 'SUFRIÓ, PERO GANÓ', 'TRES PUNTOS SON TRES PUNTOS', 'VICTORIA CORTA',
        'MARGEN MÍNIMO', 'FINAL APRETADO', 'TRIUNFO ESTRECHO', 'LO SACÓ ADELANTE', 'DIFERENCIA JUSTA',
      ],
      headlines: [
        '{equipo} SUPERA POR POCO A {rival}',
        '{equipo} GANA POR LA MÍNIMA',
        'UN GOL SEPARÓ A {equipo} DE {rival}',
        '{equipo} RESUELVE UN MARCADOR AJUSTADO',
        '{equipo} FESTEJA ANTE {rival}',
        'TRIUNFO ESTRECHO DE {equipo}',
        '{equipo} MARCA LA DIFERENCIA JUSTA',
        '{equipo} SE QUEDA CON UN RESULTADO CERRADO',
        '{equipo} VENCE A {rival} POR UN GOL',
        'VENTAJA MÍNIMA PARA {equipo}',
      ],
      bodies: [
        '{equipo} derrotó {resultado} a {rival}. La diferencia final fue de un gol.',
        'Un gol de distancia decidió el triunfo de {equipo} por {resultado} frente a {rival}.',
        '{equipo} se impuso a {rival} con marcador {resultado}.',
        'El duelo terminó {resultado}, con victoria ajustada para {equipo} sobre {rival}.',
        '{equipo} consiguió una victoria por la mínima ante {rival}: {resultado}.',
        '{equipo} sumó ante {rival} después de un cerrado {resultado}.',
        '{equipo} sacó una diferencia de un gol y venció {resultado} a {rival}.',
        template('La cuenta favoreció {resultado} a {equipo} sobre {rival} en {jornada}.', ['jornada']),
        template('{equipo} cerró {jornada} con un triunfo {resultado} frente a {rival}.', ['jornada']),
        template('{competicion} dejó una victoria ajustada de {equipo}: {resultado} ante {rival}.', ['competicion']),
      ],
    },
    normal: {
      labels: [
        '¡VICTORIA!', 'TRIUNFO CONFIRMADO', 'TAREA CUMPLIDA', 'RESULTADO POSITIVO', 'SUMA DE A TRES',
        'BUENA JORNADA', 'PARTIDO GANADO', 'OBJETIVO CUMPLIDO', 'MARCADOR A FAVOR', 'HAY FESTEJO',
      ],
      headlines: [
        '{equipo} SE LLEVA EL TRIUNFO',
        '{equipo} SUPERA A {rival}',
        '{equipo} FIRMA UNA NUEVA VICTORIA',
        '{equipo} RESUELVE SU PARTIDO ANTE {rival}',
        'VICTORIA DE {equipo} FRENTE A {rival}',
        '{equipo} CIERRA CON EL MARCADOR A FAVOR',
        '{equipo} SE QUEDA CON EL PARTIDO',
        '{equipo} SUMA UN TRIUNFO ANTE {rival}',
        'RESULTADO POSITIVO PARA {equipo}',
        '{equipo} TERMINA POR DELANTE DE {rival}',
      ],
      bodies: [
        '{equipo} venció {resultado} a {rival}.',
        'El partido terminó {resultado} a favor de {equipo} frente a {rival}.',
        '{equipo} consiguió la victoria ante {rival} con un marcador de {resultado}.',
        'La cuenta favoreció a {equipo}, que derrotó {resultado} a {rival}.',
        '{equipo} completó su compromiso ante {rival} con victoria por {resultado}.',
        '{equipo} terminó por delante de {rival} en el resultado {resultado}.',
        template('{equipo} se impuso {resultado} a {rival} en {jornada}.', ['jornada']),
        template('El resultado de {jornada} dejó un triunfo de {equipo} por {resultado} sobre {rival}.', ['jornada']),
        template('{equipo} celebró en {competicion} tras vencer {resultado} a {rival}.', ['competicion']),
        template('{competicion} registró una victoria de {equipo} por {resultado} ante {rival}.', ['competicion']),
      ],
    },
    big: {
      labels: [
        '¡GOLEADA!', '¡APLANADORA!', 'NOCHE REDONDA', 'FESTIVAL DE GOLES', 'VICTORIA CONTUNDENTE',
        'MARCADOR AMPLIO', 'TRIUNFO CATEGÓRICO', 'MUCHOS GOLES', 'DIFERENCIA CLARA', 'CUENTA ABULTADA',
      ],
      headlines: [
        '{equipo} GOLEA A {rival}',
        '{equipo} FIRMA UN TRIUNFO CONTUNDENTE',
        '{equipo} SE IMPONE POR AMPLIO MARGEN',
        '{equipo} MARCA UNA GRAN DIFERENCIA',
        'GOLEADA DE {equipo} ANTE {rival}',
        '{equipo} SUPERA CON CLARIDAD A {rival}',
        '{equipo} CIERRA UN MARCADOR ABULTADO',
        'FESTIVAL DE GOLES DE {equipo}',
        '{equipo} CONSIGUE UNA VICTORIA AMPLIA',
        '{equipo} RESUELVE CON GOLES',
      ],
      bodies: [
        '{equipo} derrotó {resultado} a {rival}, con una diferencia de tres o más goles.',
        'El marcador {resultado} confirmó una victoria amplia de {equipo} frente a {rival}.',
        '{equipo} se impuso con claridad en la cuenta ante {rival}: {resultado}.',
        '{equipo} consiguió una goleada frente a {rival} al cerrar el partido {resultado}.',
        '{equipo} marcó una diferencia amplia y venció {resultado} a {rival}.',
        'Con varios goles de distancia, {equipo} superó {resultado} a {rival}.',
        template('En {jornada} se registró un triunfo contundente de {equipo} por {resultado} ante {rival}.', ['jornada']),
        template('El encuentro de {jornada} terminó {resultado} para {equipo} sobre {rival}.', ['jornada']),
        template('{equipo} dejó un resultado categórico en {competicion}: {resultado} ante {rival}.', ['competicion']),
        template('{competicion} tuvo goleada de {equipo}, que venció {resultado} a {rival}.', ['competicion']),
      ],
    },
  },
  defeat: {
    narrow: {
      labels: [
        'CAÍDA AJUSTADA', 'POR MUY POCO', 'NO ALCANZÓ', 'MARGEN EN CONTRA', 'DERROTA CORTA',
        'FINAL ESTRECHO', 'UN GOL DE DISTANCIA', 'RESULTADO ADVERSO', 'CERCA EN LA CUENTA', 'DIFERENCIA MÍNIMA',
      ],
      headlines: [
        '{equipo} CAE POR POCO ANTE {rival}',
        '{equipo} PIERDE POR LA MÍNIMA',
        'UN GOL DEJA ABAJO A {equipo}',
        '{equipo} CIERRA CON DERROTA AJUSTADA',
        '{rival} SUPERA POR POCO A {equipo}',
        'CAÍDA ESTRECHA DE {equipo}',
        '{equipo} QUEDA A UN GOL DE {rival}',
        'MARGEN MÍNIMO EN CONTRA DE {equipo}',
        '{equipo} CEDE UN PARTIDO CERRADO',
        'RESULTADO AJUSTADO PARA {equipo} Y {rival}',
      ],
      bodies: [
        '{equipo} perdió {resultado} frente a {rival}; la diferencia fue de un gol.',
        'El marcador terminó {resultado} en contra de {equipo} ante {rival}.',
        '{equipo} cayó por la mínima frente a {rival}: {resultado}.',
        '{rival} se impuso a {equipo} por un gol de diferencia en el {resultado}.',
        'La cuenta dejó a {equipo} un gol por debajo de {rival}: {resultado}.',
        '{equipo} cedió ante {rival} por una diferencia corta; el resultado fue {resultado}.',
        template('En {jornada}, {equipo} cayó ante {rival} por un ajustado {resultado}.', ['jornada']),
        template('La cuenta de {jornada} favoreció a {rival} sobre {equipo}: {resultado}.', ['jornada']),
        template('{equipo} perdió por la mínima ante {rival} en {competicion}: {resultado}.', ['competicion']),
        template('{competicion} registró un estrecho {resultado} en contra de {equipo} frente a {rival}.', ['competicion']),
      ],
    },
    normal: {
      labels: [
        'DERROTA', 'RESULTADO ADVERSO', 'TOCÓ PERDER', 'JORNADA DIFÍCIL', 'MARCADOR EN CONTRA',
        'SIN PUNTOS', 'CAÍDA', 'PARTIDO PERDIDO', 'A PASAR PÁGINA', 'NO FUE ESTA VEZ',
      ],
      headlines: [
        '{equipo} CAE ANTE {rival}',
        '{equipo} NO PUDO CON {rival}',
        'DERROTA DE {equipo} FRENTE A {rival}',
        '{equipo} TERMINA ABAJO EN EL MARCADOR',
        '{rival} SUPERA A {equipo}',
        '{equipo} CIERRA CON RESULTADO ADVERSO',
        'TROPIEZO DE {equipo} ANTE {rival}',
        '{equipo} CEDE EL PARTIDO',
        'LA CUENTA NO FAVORECIÓ A {equipo}',
        '{equipo} PIERDE SU CRUCE CON {rival}',
      ],
      bodies: [
        '{equipo} perdió {resultado} frente a {rival}.',
        'El marcador terminó {resultado} en contra de {equipo} ante {rival}.',
        '{rival} se impuso {resultado} a {equipo}.',
        '{equipo} no consiguió superar a {rival} y terminó con marcador {resultado}.',
        'El partido concluyó {resultado}, adverso para {equipo} frente a {rival}.',
        '{equipo} registró una derrota ante {rival} luego del resultado {resultado}.',
        template('En {jornada}, {equipo} perdió {resultado} ante {rival}.', ['jornada']),
        template('{rival} terminó por delante de {equipo} en {jornada}: {resultado}.', ['jornada']),
        template('{equipo} cayó {resultado} frente a {rival} en {competicion}.', ['competicion']),
        template('{competicion} registró un resultado adverso para {equipo}: {resultado} ante {rival}.', ['competicion']),
      ],
    },
    big: {
      labels: [
        'DURA CAÍDA', 'RESULTADO CONTUNDENTE', 'JORNADA COMPLICADA', 'MARCADOR AMPLIO', 'A PASAR PÁGINA',
        'DIFERENCIA ABULTADA', 'NOCHE DIFÍCIL', 'GOLPE EN LA CUENTA', 'RESULTADO SEVERO', 'TOCÓ REMAR',
      ],
      headlines: [
        '{equipo} SUFRE UNA DERROTA AMPLIA',
        '{equipo} CAE CON DIFERENCIA ANTE {rival}',
        '{rival} GOLEA A {equipo}',
        'MARCADOR DURO PARA {equipo}',
        '{equipo} NO PUDO FRENAR LA CUENTA DE {rival}',
        'CAÍDA CONTUNDENTE DE {equipo}',
        '{equipo} TERMINA LEJOS EN EL MARCADOR',
        '{rival} MARCA UNA AMPLIA DIFERENCIA',
        '{equipo} RECIBE UN RESULTADO ABULTADO',
        'DUELO ADVERSO PARA {equipo}',
      ],
      bodies: [
        '{equipo} cayó {resultado} ante {rival}, por una diferencia de tres o más goles.',
        'El resultado {resultado} dejó una derrota amplia de {equipo} frente a {rival}.',
        '{rival} superó con claridad a {equipo} en el marcador: {resultado}.',
        '{equipo} no pudo evitar una diferencia amplia frente a {rival} y perdió {resultado}.',
        '{equipo} terminó a tres o más goles de {rival} en el resultado {resultado}.',
        'La cuenta favoreció ampliamente a {rival} sobre {equipo}: {resultado}.',
        template('En {jornada} se registró un marcador abultado en contra de {equipo}: {resultado} ante {rival}.', ['jornada']),
        template('El partido de {jornada} concluyó {resultado}, con derrota amplia para {equipo}.', ['jornada']),
        template('{rival} venció con margen a {equipo} en {competicion}; la cuenta terminó {resultado}.', ['competicion']),
        template('{competicion} dejó un resultado contundente contra {equipo}: {resultado} frente a {rival}.', ['competicion']),
      ],
    },
  },
  draw: {
    goalless: {
      labels: [
        'CERO A CERO', 'SIN GOLES', 'MARCADOR EN BLANCO', 'PUNTOS REPARTIDOS', 'TABLAS SIN GOLES',
        'IGUALDAD TOTAL', 'NADIE ANOTÓ', 'EMPATE A CERO', 'CUENTA CERRADA', 'SIN DIFERENCIAS',
      ],
      headlines: [
        '{equipo} Y {rival} TERMINAN SIN GOLES',
        'CERO A CERO ENTRE {equipo} Y {rival}',
        '{equipo} FIRMA TABLAS CON {rival}',
        'MARCADOR EN BLANCO PARA {equipo} Y {rival}',
        'SIN GOLES EN EL CRUCE DE {equipo}',
        '{equipo} Y {rival} REPARTEN PUNTOS',
        'NINGÚN GOL ENTRE {equipo} Y {rival}',
        'IGUALDAD A CERO PARA {equipo}',
        '{equipo} CIERRA 0-0 ANTE {rival}',
        'EL MARCADOR NO SE MOVIÓ ENTRE {equipo} Y {rival}',
      ],
      bodies: [
        '{equipo} y {rival} empataron {resultado}.',
        'El encuentro entre {equipo} y {rival} terminó sin goles: {resultado}.',
        '{equipo} repartió el resultado con {rival} después de un {resultado}.',
        'No hubo ganador ni goles entre {equipo} y {rival}; la cuenta fue {resultado}.',
        'El marcador final quedó en blanco para {equipo} y {rival}: {resultado}.',
        '{equipo} y {rival} cerraron su compromiso con igualdad {resultado}.',
        template('En {jornada}, {equipo} y {rival} terminaron sin goles.', ['jornada']),
        template('El cruce de {jornada} terminó {resultado} para {equipo} y {rival}.', ['jornada']),
        template('{competicion} registró un empate a cero entre {equipo} y {rival}.', ['competicion']),
        template('{equipo} y {rival} repartieron puntos sin goles en {competicion}.', ['competicion']),
      ],
    },
    normal: {
      labels: [
        '¡EMPATE!', 'PUNTOS REPARTIDOS', 'TABLAS', 'SIN DIFERENCIAS', 'MARCADOR IGUALADO',
        'TODO PAREJO', 'EMPATE CONFIRMADO', 'MISMA CUENTA', 'NO HUBO GANADOR', 'IGUALDAD FINAL',
      ],
      headlines: [
        '{equipo} Y {rival} REPARTEN EL RESULTADO',
        '{equipo} EMPATA CON {rival}',
        'NO HUBO DIFERENCIAS ENTRE {equipo} Y {rival}',
        '{equipo} Y {rival} TERMINAN IGUALADOS',
        'EMPATE EN EL CRUCE DE {equipo} Y {rival}',
        '{equipo} FIRMA TABLAS ANTE {rival}',
        'MARCADOR PAREJO PARA {equipo} Y {rival}',
        '{equipo} Y {rival} CIERRAN SIN GANADOR',
        'IGUALDAD ENTRE {equipo} Y {rival}',
        'EL DUELO DE {equipo} TERMINA EN EMPATE',
      ],
      bodies: [
        '{equipo} y {rival} empataron {resultado}.',
        'El encuentro entre {equipo} y {rival} terminó igualado {resultado}.',
        '{equipo} repartió el resultado con {rival} tras el {resultado}.',
        'No hubo ganador: {equipo} y {rival} cerraron {resultado}.',
        'El marcador final fue {resultado} entre {equipo} y {rival}.',
        '{equipo} no logró separarse de {rival} y el partido terminó {resultado}.',
        template('En {jornada}, {equipo} y {rival} empataron {resultado}.', ['jornada']),
        template('La cuenta de {jornada} quedó {resultado} para {equipo} y {rival}.', ['jornada']),
        template('{competicion} registró un empate entre {equipo} y {rival}, con resultado {resultado}.', ['competicion']),
        template('{equipo} y {rival} compartieron el marcador {resultado} en {competicion}.', ['competicion']),
      ],
    },
    crazy: {
      labels: [
        '¡PARTIDAZO!', 'LLUVIA DE GOLES', '¡PERO QUÉ FUE ESTO!', 'GOL VA, GOL VIENE', 'EMPATE DE LOCURA',
        'FESTIVAL DE GOLES', 'TABLAS CON GOLES', 'MARCADOR DE INFARTO', 'GOLES PARA TODOS', 'NADIE AFLOJÓ',
      ],
      headlines: [
        '{equipo} Y {rival} EMPATAN CON MUCHOS GOLES',
        'FESTIVAL SIN GANADOR ENTRE {equipo} Y {rival}',
        '{equipo} Y {rival} FIRMAN UN EMPATE ABULTADO',
        'LLUVIA DE GOLES ENTRE {equipo} Y {rival}',
        'UN EMPATE CARGADO DE GOLES',
        '{equipo} Y {rival} NO SE SACAN VENTAJA',
        'MARCADOR ALTO E IGUALADO',
        'EMPATE CON SEIS O MÁS GOLES',
        '{equipo} Y {rival} DEJAN UNA CUENTA LLENA DE GOLES',
        'LA RED SE MOVIÓ, PERO NO HUBO GANADOR',
      ],
      bodies: [
        '{equipo} y {rival} igualaron {resultado}, con seis o más goles en total.',
        'El partido terminó {resultado}: muchos goles y ninguna diferencia entre {equipo} y {rival}.',
        '{equipo} y {rival} protagonizaron un empate de marcador alto: {resultado}.',
        'Hubo goles para ambos lados en el empate {resultado} de {equipo} frente a {rival}.',
        'El cruce entre {equipo} y {rival} superó los cinco goles y terminó {resultado}.',
        '{equipo} y {rival} cerraron un partido de alta anotación con resultado {resultado}.',
        template('En {jornada}, {equipo} y {rival} firmaron una igualdad llena de goles: {resultado}.', ['jornada']),
        template('La cuenta de {jornada} fue {resultado} entre {equipo} y {rival}.', ['jornada']),
        template('{competicion} registró una igualdad con muchos goles: {equipo} {resultado} {rival}.', ['competicion']),
        template('Los goles se repartieron en {competicion}: {equipo} y {rival} terminaron {resultado}.', ['competicion']),
      ],
    },
  },
  transfer: {
    arrival: {
      labels: [
        '¡NUEVO REFUERZO!', 'LLEGÓ AL CLUB', 'ALTA CONFIRMADA', 'NUEVA CAMISETA', 'INCORPORACIÓN',
        'SE SUMA AL PLANTEL', 'FICHAJE CERRADO', 'CARAS NUEVAS', 'BIENVENIDO', 'MERCADO ACTIVO',
      ],
      headlines: [
        '{jugador} ES NUEVO JUGADOR DE {equipoDestino}',
        '{equipoDestino} INCORPORA A {jugador}',
        '{jugador} LLEGA A {equipoDestino}',
        '{equipoDestino} SUMA A {jugador}',
        'NUEVO DESTINO PARA {jugador}',
        '{jugador} VESTIRÁ LA CAMISETA DE {equipoDestino}',
        'REFUERZO CONFIRMADO PARA {equipoDestino}',
        '{equipoDestino} RECIBE A {jugador}',
        '{jugador} SE UNE A {equipoDestino}',
        'HAY NUEVA INCORPORACIÓN EN {equipoDestino}',
      ],
      bodies: [
        '{equipoDestino} incorporó a {jugador}, procedente de {equipoOrigen}.',
        '{jugador} tiene nuevo destino y pasa de {equipoOrigen} a {equipoDestino}.',
        'Se confirmó la llegada de {jugador} a {equipoDestino} desde {equipoOrigen}.',
        '{equipoDestino} suma a {jugador} tras su salida de {equipoOrigen}.',
        'El cambio de club de {jugador} lo lleva desde {equipoOrigen} hasta {equipoDestino}.',
        '{jugador} deja {equipoOrigen} y se incorpora a {equipoDestino}.',
        '{equipoDestino} presenta a {jugador} como nueva incorporación procedente de {equipoOrigen}.',
        '{jugador} continuará su recorrido en {equipoDestino} después de dejar {equipoOrigen}.',
        template('{competicion} registró la llegada de {jugador} a {equipoDestino} desde {equipoOrigen}.', ['competicion']),
        template('El mercado de {competicion} lleva a {jugador} de {equipoOrigen} a {equipoDestino}.', ['competicion']),
      ],
    },
    departure: {
      labels: [
        'CAMBIO DE RUMBO', 'SALE DEL CLUB', 'NUEVO CAMINO', 'DESPEDIDA', 'CAMBIO DE CAMISETA',
        'BAJA CONFIRMADA', 'FIN DE ETAPA', 'RUMBO NUEVO', 'MOVIMIENTO DE MERCADO', 'CONTINÚA SU CAMINO',
      ],
      headlines: [
        '{jugador} DEJA {equipoOrigen}',
        '{equipoOrigen} DESPIDE A {jugador}',
        'NUEVO RUMBO PARA {jugador}',
        '{jugador} CAMBIA DE CAMISETA',
        'TERMINA LA ETAPA DE {jugador} EN {equipoOrigen}',
        '{jugador} CONTINUARÁ EN {equipoDestino}',
        '{equipoOrigen} CONFIRMA LA SALIDA DE {jugador}',
        '{jugador} PARTE RUMBO A {equipoDestino}',
        'CAMBIO DE CLUB PARA {jugador}',
        '{jugador} CIERRA SU PASO POR {equipoOrigen}',
      ],
      bodies: [
        '{jugador} deja {equipoOrigen} y continuará en {equipoDestino}.',
        '{equipoOrigen} confirmó la salida de {jugador}, cuyo nuevo club será {equipoDestino}.',
        'La etapa de {jugador} en {equipoOrigen} termina con su paso a {equipoDestino}.',
        '{jugador} cambia de rumbo: sale de {equipoOrigen} para sumarse a {equipoDestino}.',
        '{equipoDestino} será el próximo club de {jugador} tras su salida de {equipoOrigen}.',
        'El recorrido de {jugador} continúa en {equipoDestino} después de dejar {equipoOrigen}.',
        '{jugador} se despide de {equipoOrigen} y cambia su camiseta por la de {equipoDestino}.',
        '{equipoOrigen} registra la baja de {jugador}, que pasa a {equipoDestino}.',
        template('El mercado de {competicion} confirmó la salida de {jugador} desde {equipoOrigen} hacia {equipoDestino}.', ['competicion']),
        template('{jugador} abre una nueva etapa en {competicion}: deja {equipoOrigen} y llega a {equipoDestino}.', ['competicion']),
      ],
    },
    move: {
      labels: [
        '¡FICHAJE!', 'MERCADO DE PASES', 'TRASPASO CONFIRMADO', 'CAMBIO DE CLUB', 'NUEVO DESTINO',
        'OPERACIÓN CERRADA', 'MERCADO EN MARCHA', 'MOVIMIENTO OFICIAL', 'CAMBIO DE CAMISETA', 'PASE CONFIRMADO',
      ],
      headlines: [
        '{jugador} CAMBIA {equipoOrigen} POR {equipoDestino}',
        'TRASPASO DE {jugador} A {equipoDestino}',
        '{equipoOrigen} Y {equipoDestino} MUEVEN EL MERCADO',
        '{jugador} YA TIENE NUEVO CLUB',
        'NUEVO DESTINO PARA {jugador}',
        '{jugador} PASA DE {equipoOrigen} A {equipoDestino}',
        'MOVIMIENTO CONFIRMADO ENTRE {equipoOrigen} Y {equipoDestino}',
        '{equipoDestino} ES EL NUEVO CLUB DE {jugador}',
        '{jugador} CAMBIA DE CAMISETA',
        'EL MERCADO LLEVA A {jugador} A {equipoDestino}',
      ],
      bodies: [
        '{jugador} pasó de {equipoOrigen} a {equipoDestino}.',
        'El mercado confirmó el cambio de club de {jugador}: deja {equipoOrigen} y llega a {equipoDestino}.',
        '{jugador} tiene nuevo destino tras concretarse su paso desde {equipoOrigen} hacia {equipoDestino}.',
        'Quedó registrado el movimiento de {jugador} entre {equipoOrigen} y {equipoDestino}.',
        '{equipoOrigen} traspasó a {jugador}, que continuará en {equipoDestino}.',
        '{jugador} cambia de camiseta y pasa de {equipoOrigen} a {equipoDestino}.',
        '{equipoDestino} incorpora a {jugador} en un movimiento desde {equipoOrigen}.',
        'El nuevo club de {jugador} será {equipoDestino}, después de su paso por {equipoOrigen}.',
        template('{competicion} registró el traspaso de {jugador} entre {equipoOrigen} y {equipoDestino}.', ['competicion']),
        template('El mercado de {competicion} mueve a {jugador} desde {equipoOrigen} hasta {equipoDestino}.', ['competicion']),
      ],
    },
  },
  sanction: {
    player: {
      labels: [
        'SANCIONADO', 'BAJA CONFIRMADA', 'NO ESTARÁ DISPONIBLE', 'SANCIÓN OFICIAL', 'FUERA DE JUEGO',
        'CASTIGO CONFIRMADO', 'A MIRAR DESDE AFUERA', 'DECISIÓN DISCIPLINARIA', 'TURNO DE CUMPLIR', 'AUSENCIA CONFIRMADA',
      ],
      headlines: [
        '{jugador} RECIBE UNA SANCIÓN',
        'SANCIÓN CONFIRMADA PARA {jugador}',
        '{jugador} NO ESTARÁ DISPONIBLE',
        '{jugador} DEBERÁ CUMPLIR UNA SANCIÓN',
        'DECISIÓN DISCIPLINARIA SOBRE {jugador}',
        template('{equipo} TENDRÁ LA BAJA DE {jugador}', ['equipo']),
        template('{jugador} QUEDA FUERA POR {partidosSancion} PARTIDO(S)', ['partidosSancion']),
        template('CASTIGO DE {partidosSancion} PARTIDO(S) PARA {jugador}', ['partidosSancion']),
        template('{jugador} SERÁ BAJA EN {equipo}', ['equipo']),
        template('{equipo} NO CONTARÁ CON {jugador}', ['equipo']),
      ],
      bodies: [
        '{jugador} recibió una sanción oficial.',
        'La información disponible confirma una sanción para {jugador}.',
        '{jugador} deberá cumplir la medida disciplinaria registrada.',
        template('{jugador}, de {equipo}, recibió una sanción.', ['equipo']),
        template('{equipo} tendrá la ausencia de {jugador} por una decisión disciplinaria.', ['equipo']),
        template('{jugador} deberá cumplir {partidosSancion} partido(s) de suspensión.', ['partidosSancion']),
        template('La sanción aplicada a {jugador} contempla {partidosSancion} partido(s) fuera.', ['partidosSancion']),
        template('{equipo} no podrá contar con {jugador} durante {partidosSancion} partido(s).', ['equipo', 'partidosSancion']),
        template('{competicion} registra una sanción de {partidosSancion} partido(s) para {jugador}.', ['competicion', 'partidosSancion']),
        template('{tipoSancion}: {jugador} figura como sancionado en {competicion}.', ['tipoSancion', 'competicion']),
      ],
    },
    club: {
      labels: [
        'SANCIÓN AL CLUB', 'DECISIÓN OFICIAL', 'MEDIDA DISCIPLINARIA', 'CLUB SANCIONADO', 'RESOLUCIÓN CONFIRMADA',
        'INFORME OFICIAL', 'SANCIÓN CONFIRMADA', 'NOVEDAD DISCIPLINARIA', 'MEDIDA REGISTRADA', 'PARTE OFICIAL',
      ],
      headlines: [
        '{equipo} RECIBE UNA SANCIÓN',
        'SANCIÓN CONFIRMADA PARA {equipo}',
        'DECISIÓN DISCIPLINARIA SOBRE {equipo}',
        '{equipo} FIGURA EN EL PARTE DISCIPLINARIO',
        'MEDIDA OFICIAL PARA {equipo}',
        'RESOLUCIÓN CONFIRMADA SOBRE {equipo}',
        '{equipo} ES NOTIFICADO DE UNA SANCIÓN',
        'NOVEDAD DISCIPLINARIA PARA {equipo}',
        'EL PARTE OFICIAL INCLUYE A {equipo}',
        'SE REGISTRA UNA SANCIÓN PARA {equipo}',
      ],
      bodies: [
        '{equipo} recibió una sanción según la información oficial disponible.',
        'Se confirmó una medida disciplinaria aplicada directamente a {equipo}.',
        'El registro oficial informa una sanción para {equipo}.',
        '{equipo} figura como destinatario de una resolución disciplinaria.',
        'La actividad de la liga incorporó una sanción correspondiente a {equipo}.',
        template('{equipo} recibió la sanción de tipo “{tipoSancion}”.', ['tipoSancion']),
        template('La medida “{tipoSancion}” fue registrada para {equipo}.', ['tipoSancion']),
        template('{competicion} confirmó una sanción aplicada a {equipo}.', ['competicion']),
        template('El parte de {competicion} incluye una medida disciplinaria para {equipo}.', ['competicion']),
        template('{equipo} recibió una resolución de tipo “{tipoSancion}” en {competicion}.', ['tipoSancion', 'competicion']),
      ],
    },
  },
};
