import { apiClient } from './client.js';

const get = (path, query, signal) => apiClient.get(path, { query, signal });

export const endpoints = {
  health: signal => get('/health', null, signal),
  home: signal => get('/home', null, signal),
  activity: (query, signal) => get('/activity', query, signal),
  teams: (query, signal) => get('/teams', query, signal),
  team: (teamId, signal) => get(`/teams/${teamId}`, null, signal),
  teamSquad: (teamId, signal) => get(`/teams/${teamId}/squad`, null, signal),
  teamMatches: (teamId, signal) => get(`/teams/${teamId}/matches`, null, signal),
  presidents: (query, signal) => get('/presidents', query, signal),
  coaches: (query, signal) => get('/coaches', query, signal),
  coach: (coachId, signal) => get(`/coaches/${coachId}`, null, signal),
  nationalTeams: (query, signal) => get('/national-teams', query, signal),
  squadRankings: (query, signal) => get('/rankings/squads', query, signal),
  history: (entityType, entityId, query, signal) => get(`/history/${entityType}/${entityId}`, query, signal),
  divisions: signal => get('/divisions', null, signal),
  players: (query, signal) => get('/players', query, signal),
  player: (playerId, signal) => get(`/players/${playerId}`, null, signal),
  tournaments: (query, signal) => get('/tournaments', query, signal),
  tournament: (tournamentId, signal) => get(`/tournaments/${tournamentId}`, null, signal),
  standings: (tournamentId, query, signal) => get(`/tournaments/${tournamentId}/standings`, query, signal),
  fixtures: (tournamentId, signal) => get(`/tournaments/${tournamentId}/fixtures`, null, signal),
  bracket: (tournamentId, signal) => get(`/tournaments/${tournamentId}/bracket`, null, signal),
  scorers: (tournamentId, signal) => get(`/tournaments/${tournamentId}/scorers`, null, signal),
  matches: (query, signal) => get('/matches', query, signal),
  match: (matchId, signal) => get(`/matches/${matchId}`, null, signal),
  transfers: (query, signal) => get('/market/transfers', query, signal),
  trades: (query, signal) => get('/market/trades', query, signal),
  freeAgents: (query, signal) => get('/market/free-agents', query, signal),
  createTeam: (body, signal) => apiClient.post('/teams', body, { actor: 'web', signal }),
  updateTeam: (teamId, body, signal) => apiClient.patch(`/teams/${teamId}`, body, { actor: 'web', signal }),
  updatePresident: (presidentId, body, signal) => apiClient.patch(`/presidents/${presidentId}`, body, { actor: 'web', signal }),
  createCoach: (body, signal) => apiClient.post('/coaches', body, { actor: 'web', signal }),
  updateCoach: (coachId, body, signal) => apiClient.patch(`/coaches/${coachId}`, body, { actor: 'web', signal }),
  deleteCoach: (coachId, signal) => apiClient.delete(`/coaches/${coachId}`, {}, { actor: 'web', signal }),
  uploadImage: (file, { entityType, entityId } = {}, signal) => {
    const body = new FormData();
    body.append('file', file);
    if (entityType) body.append('entityType', entityType);
    if (entityId) body.append('entityId', entityId);
    return apiClient.post('/media/images', body, { actor: 'web', signal });
  },
  deleteImage: (assetId, signal) => apiClient.delete(`/media/images/${assetId}`, {}, { actor: 'web', signal }),
  creditTeam: (teamId, body, signal) => apiClient.post(`/teams/${teamId}/credit`, body, { actor: 'web', signal }),
  debitTeam: (teamId, body, signal) => apiClient.post(`/teams/${teamId}/debit`, body, { actor: 'web', signal }),
  linkTeamDiscord: (teamId, body, signal) => apiClient.post(`/teams/${teamId}/link-discord`, body, { actor: 'web', signal }),
  updateSquadMember: (teamId, playerId, body, signal) => apiClient.patch(`/teams/${teamId}/squad/${playerId}`, body, { actor: 'web', signal }),
  updateSquadOrder: (teamId, assignments, signal) => apiClient.put(`/teams/${teamId}/squad-order`, { assignments }, { actor: 'web', signal }),
  createNationalTeam: (body, signal) => apiClient.post('/national-teams', body, { actor: 'web', signal }),
  assignNationalTeam: (teamId, clubId, signal) => apiClient.post(`/national-teams/${teamId}/assign`, { clubId }, { actor: 'web', signal }),
  releaseNationalTeam: (teamId, signal) => apiClient.post(`/national-teams/${teamId}/release`, {}, { actor: 'web', signal }),
  createPlayer: (body, signal) => apiClient.post('/players', body, { actor: 'web', signal }),
  assignPlayer: (playerId, body, signal) => apiClient.post(`/players/${playerId}/assign`, body, { actor: 'web', signal }),
  buyPlayer: (playerId, teamId, signal) => apiClient.post(`/players/${playerId}/buy`, { teamId }, { actor: 'web', signal }),
  releasePlayer: (playerId, body, signal) => apiClient.post(`/players/${playerId}/release`, body, { actor: 'web', signal }),
  createTransfer: (body, signal) => apiClient.post('/market/transfers', body, { actor: 'web', signal }),
  approveTransfer: (transferId, signal) => apiClient.post(`/market/transfers/${transferId}/approve`, {}, { actor: 'web', signal }),
  rejectTransfer: (transferId, signal) => apiClient.post(`/market/transfers/${transferId}/reject`, {}, { actor: 'web', signal }),
  reverseTransfer: (transferId, signal) => apiClient.post(`/market/transfers/${transferId}/reverse`, {}, { actor: 'web', signal }),
  createTrade: (body, signal) => apiClient.post('/market/trades', body, { actor: 'web', signal }),
  approveTrade: (tradeId, signal) => apiClient.post(`/market/trades/${tradeId}/approve`, {}, { actor: 'web', signal }),
  rejectTrade: (tradeId, signal) => apiClient.post(`/market/trades/${tradeId}/reject`, {}, { actor: 'web', signal }),
  createTournament: (body, signal) => apiClient.post('/tournaments', body, { actor: 'web', signal }),
  updateTournamentStatus: (tournamentId, status, signal) => apiClient.patch(`/tournaments/${tournamentId}/status`, { status }, { actor: 'web', signal }),
  deleteTournament: (tournamentId, signal) => apiClient.delete(`/tournaments/${tournamentId}`, { force: true }, { actor: 'web', signal }),
  addTournamentParticipation: (tournamentId, body, signal) => apiClient.post(`/tournaments/${tournamentId}/participations`, body, { actor: 'web', signal }),
  drawTournament: (tournamentId, groups, signal) => apiClient.post(`/tournaments/${tournamentId}/draw`, { groups }, { actor: 'web', signal }),
  generateRoundRobin: (tournamentId, body, signal) => apiClient.post(`/tournaments/${tournamentId}/fixtures/round-robin`, body, { actor: 'web', signal }),
  generateGroupFixtures: (tournamentId, body, signal) => apiClient.post(`/tournaments/${tournamentId}/fixtures/groups`, body, { actor: 'web', signal }),
  generateBracket: (tournamentId, body, signal) => apiClient.post(`/tournaments/${tournamentId}/bracket`, body, { actor: 'web', signal }),
  advanceBracket: (tournamentId, signal) => apiClient.post(`/tournaments/${tournamentId}/bracket/advance`, {}, { actor: 'web', signal }),
  generateCupQuarterfinals: (tournamentId, signal) => apiClient.post(`/tournaments/${tournamentId}/cup-quarterfinals`, {}, { actor: 'web', signal }),
  generateWorldRoundOf16: (tournamentId, signal) => apiClient.post(`/tournaments/${tournamentId}/world-round-of-16`, {}, { actor: 'web', signal }),
  initializeDivisions: (firstDivisionTeamIds, signal) => apiClient.post('/divisions/initialize', { firstDivisionTeamIds }, { actor: 'web', signal }),
  applyPromotion: (tournamentId, signal) => apiClient.post(`/tournaments/${tournamentId}/promotion`, {}, { actor: 'web', signal }),
  applyDivisionMovements: (tournamentId, signal) => apiClient.post(`/tournaments/${tournamentId}/division-movements`, {}, { actor: 'web', signal }),
  createMatch: (body, signal) => apiClient.post('/matches', body, { actor: 'web', signal }),
  startMatch: (matchId, signal) => apiClient.post(`/matches/${matchId}/start`, {}, { actor: 'web', signal }),
  finishMatch: (matchId, signal) => apiClient.post(`/matches/${matchId}/finish`, {}, { actor: 'web', signal }),
  cancelMatch: (matchId, signal) => apiClient.post(`/matches/${matchId}/cancel`, {}, { actor: 'web', signal }),
  reopenMatch: (matchId, signal) => apiClient.post(`/matches/${matchId}/reopen`, {}, { actor: 'web', signal }),
  setMatchResult: (matchId, body, signal) => apiClient.post(`/matches/${matchId}/result`, body, { actor: 'web', signal }),
  addMatchGoal: (matchId, body, signal) => apiClient.post(`/matches/${matchId}/goals`, body, { actor: 'web', signal }),
  deleteMatchGoal: (matchId, goalId, signal) => apiClient.delete(`/matches/${matchId}/goals/${goalId}`, {}, { actor: 'web', signal }),
  addMatchRedCard: (matchId, body, signal) => apiClient.post(`/matches/${matchId}/red-cards`, body, { actor: 'web', signal }),
  setMatchWinner: (matchId, body, signal) => apiClient.post(`/matches/${matchId}/winner`, body, { actor: 'web', signal }),
};
