import React, { useEffect, useLayoutEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './home.css';

const menu = [
  ['Inicio', 'ball', 'home'], ['Resultados', 'cup'], ['Partidos', 'pitch'], ['Clasificación', 'chart'],
  ['Equipos', 'shirt', 'teams'], ['Transferencias', 'arrows'], ['Sanciones', 'card'], ['Torneos', 'cup'], ['Noticias', 'news'],
];
const children = { Partidos: ['Jugados', 'Pendientes'], Equipos: ['Plantillas', 'Presupuestos', 'Presidente', 'DT', 'Emblemas'] };
const list = value => Array.isArray(value) ? value : [];
const gp = value => typeof value === 'number' ? value.toLocaleString('es-CL') : '—';
const api = async path => { const res = await fetch(`http://127.0.0.1:5175/api${path}`); if (!res.ok) throw new Error(String(res.status)); return (await res.json()).data; };

function Icon({ type }) {
  const shapes = {
    ball: <><circle cx="24" cy="24" r="19" fill="#f6f4e8" stroke="#0b101a" strokeWidth="3"/><path d="m24 14 10 7-4 12H18l-4-12 10-7ZM8 14l8 1-2 6-9 3m19 19-6-10m19-19-3 7 9 3M24 5v9m6 19 9 5M9 38l9-5" fill="#080d15" stroke="#080d15" strokeWidth="2"/></>,
    cup: <><path d="M13 5h22v14c0 10-4 15-11 15s-11-5-11-15Zm0 3H5v8c0 9 5 12 12 12M35 8h8v8c0 9-5 12-12 12" fill="#ffd71b" stroke="#e49b0a" strokeWidth="2"/><path d="M21 31h6v10h9v4H12v-4h9Z" fill="#ffda21"/></>,
    pitch: <><path d="M3 8h42v33H3Z M24 8v33M3 16h8v17H3m42-17h-8v17h8" fill="none" stroke="#f4f0db" strokeWidth="2"/><circle cx="24" cy="24" r="7" fill="none" stroke="#f4f0db" strokeWidth="2"/></>,
    chart: <><path d="M6 29h7v15H6Zm14-10h7v25h-7ZM34 6h7v38h-7Z" fill="#ffd925"/></>,
    shirt: <path d="m15 6-5 2-8 9 8 8 6-5v25h22V20l6 5 6-8-8-9-8-2c-1 7-17 7-19 0Z" transform="translate(-2 0)" fill="#f5f2e5" stroke="#9baabb"/>,
    arrows: <><path d="M4 13h30V5l12 12-12 12v-8H4Zm40 20H14v-8L2 37l12 11v-8h30Z" fill="#ffdc23"/></>,
    card: <path d="m17 5 22 3-6 35-23-3Z" fill="#ff1523" stroke="#100e19" strokeWidth="3"/>,
    news: <><path d="M10 5h30v36H10Zm-6 5v35h30" stroke="#f4f0db" strokeWidth="3" fill="none"/><path d="M16 12h18v4H16Zm0 9h18m-18 6h18m-18 6h18" stroke="#f4f0db" strokeWidth="2"/></>,
  };
  return <svg className="menu-icon" viewBox="0 0 48 48" aria-hidden="true">{shapes[type]}</svg>;
}

function TeamMark({ team, className = '' }) {
  return team?.imageUrl ? <img className={`team-mark ${className}`} src={team.imageUrl} alt={`Escudo de ${team.name}`} /> : <span className={`team-mark emoji-mark ${className}`} aria-label={`Emblema de ${team?.name ?? 'equipo'}`}>{team?.emoji ?? '⚽'}</span>;
}

function App() {
  const [scale, setScale] = useState(1), [view, setView] = useState('home');
  const [league, setLeague] = useState({ home: null, teams: [], standings: [] });
  const [selected, setSelected] = useState(null), [detail, setDetail] = useState(null), [squad, setSquad] = useState([]);
  const [state, setState] = useState({ loading: true, error: '' });
  useLayoutEffect(() => { const resize = () => setScale(Math.min(innerWidth / 1536, 1.25)); resize(); addEventListener('resize', resize); return () => removeEventListener('resize', resize); }, []);
  useEffect(() => { let cancelled = false; Promise.all([api('/home'), api('/teams?page=1&pageSize=100')]).then(async ([home, teams]) => { const tournament = list(home?.activeTournaments)[0]; const standings = tournament?.id ? await api(`/tournaments/${tournament.id}/standings`).catch(() => []) : []; if (!cancelled) { setLeague({ home, teams: list(teams), standings: list(standings) }); setState({ loading: false, error: '' }); } }).catch(() => !cancelled && setState({ loading: false, error: 'No fue posible actualizar los datos de la liga.' })); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!selected?.id) return; let cancelled = false; setDetail(null); setSquad([]); Promise.all([api(`/teams/${selected.id}`), api(`/teams/${selected.id}/squad`)]).then(([team, roster]) => { if (!cancelled) { setDetail(team); setSquad(list(roster)); } }).catch(() => !cancelled && setState(current => ({ ...current, error: 'No fue posible cargar la ficha completa del equipo.' }))); return () => { cancelled = true; }; }, [selected?.id]);
  const indexed = useMemo(() => new Map(league.teams.map(team => [team.id, team])), [league.teams]);
  const resolve = team => ({ ...team, ...(indexed.get(team?.id ?? team?.team_id) ?? {}) });
  const tournament = list(league.home?.activeTournaments)[0], upcoming = list(league.home?.upcomingMatches).slice(0, 5), completed = list(league.home?.liveMatches).filter(match => match.status !== 'pending').slice(0, 5), lead = upcoming[0];
  const team = detail ?? selected, roster = [...squad].sort((a, b) => (a.squadOrder ?? 999) - (b.squadOrder ?? 999));
  const starters = roster.filter(player => player.section === 'starters' || (!player.section && player.squadOrder <= 11)), substitutes = roster.filter(player => player.section === 'substitutes' || (!player.section && player.squadOrder > 11));
  const choose = row => { setSelected(row); setView('team'); };
  const message = label => setState(current => ({ ...current, error: `${label} se habilitará en una siguiente etapa.` }));
  const nav = <aside className="menu-column"><nav aria-label="Menú de la liga">{menu.map(([label, icon, target]) => { const active = target === view || (target === 'teams' && view === 'team'); return <div className={`nav-box ${active ? 'selected' : ''} ${children[label] ? 'with-children' : ''}`} key={label}><button className="nav-primary" aria-current={active ? 'page' : undefined} onClick={() => target ? setView(target) : message(label)}><Icon type={icon}/><span>{label}</span>{active && <span className="selection-arrow"/>}</button>{children[label] && <div className="nav-children">{children[label].map(child => <button key={child} onClick={() => target ? setView(target) : message(child)}><span>›</span>{child}</button>)}</div>}</div>; })}</nav></aside>;
  const home = <main className="newspaper"><section className="main-edition"><header className="newspaper-header"><h1><span>KOINONIA <em>e-LEAGUE</em> NEWS</span></h1><p>FÚTBOL VIRTUAL. PASIÓN REAL.</p><div className="edition-date">EN VIVO<br/><time>{tournament?.name ?? 'CARGANDO LIGA'}</time></div></header><article className="lead-story"><h2><span className="headline-team">{tournament?.name?.toUpperCase() ?? 'LA LIGA'}</span><span className="headline-result">{lead ? 'YA TIENE PARTIDO' : 'EN PREPARACIÓN'}</span></h2><div className="lead-columns"><div className="lead-copy"><p>{lead ? `La fecha ${lead.roundNumber ?? 'actual'} enfrentará a ${lead.homeTeam.name} y ${lead.awayTeam.name}. Revisa los encuentros y la clasificación oficial.` : 'La liga aún no tiene partidos próximos publicados.'}</p><blockquote>“Fútbol como antes,<br/>amigos como siempre.”</blockquote></div><figure className="lead-photo" role="img" aria-label="Jugador celebra frente a las tribunas"/></div></article></section><section className="secondary-stories"><article className="small-story transfer-story"><h3>MERCADO DE FICHAJES</h3><div className="transfer-illustration"><span className="transfer-portrait"/><span className="transfer-arrow">➜</span><span className="transfer-crest"/></div><h4>{league.home?.recentTransfers?.length ? 'MOVIMIENTOS RECIENTES' : 'SIN MOVIMIENTOS PUBLICADOS'}</h4><p>{league.home?.recentTransfers?.length ? `${league.home.recentTransfers.length} transferencia(s) registrada(s).` : 'El mercado no registra transferencias recientes.'}</p></article><article className="small-story sanction-story"><h3>CLASIFICACIÓN</h3><div className="small-columns"><span className="red-card-photo"/><div><h4><b>{league.standings[0]?.name?.toUpperCase() ?? 'CARGANDO'}</b><br/>LÍDER DE LA LIGA</h4><p>{league.standings[0] ? `${league.standings[0].points} puntos en ${league.standings[0].played} partidos.` : 'Esperando tabla oficial.'}</p></div></div></article><article className="small-story quote-story"><h3>LA FRASE DE LA FECHA</h3><div className="small-columns"><span className="coach-photo"/><div><blockquote>“Cada fecha puede cambiar la historia de la liga.”</blockquote><p className="quote-credit">– KOINONIA e-LEAGUE</p></div></div></article></section></main>;
  const teams = <main className="newspaper teams-page"><section className="team-list-paper"><header className="team-page-header"><p>BASE DE DATOS DE LA LIGA</p><h1>SELECCIÓN DE EQUIPOS</h1><span>{league.teams.length} EQUIPOS REGISTRADOS</span></header>{state.loading ? <div className="arcade-state">CARGANDO EQUIPOS...</div> : <div className="team-grid">{league.teams.map(row => <button className="team-choice" key={row.id} onClick={() => choose(row)}><TeamMark team={row}/><span><b>{row.name}</b><small>PRES. {row.president?.name ?? row.presidentName ?? 'SIN ASIGNAR'}</small><small>{row.playerCount ?? 0} JUGADORES · {row.currentDivision ?? 'LIGA ACTIVA'}</small></span><i>▶</i></button>)}</div>}</section></main>;
  const player = item => <div className="roster-row" key={item.id}><b>{String(item.squadOrder ?? '—').padStart(2, '0')}</b><span>{item.name}</span><small>{item.position ?? '—'}</small><strong>{gp(item.gpValue)} GP</strong></div>;
  const rank = league.standings.findIndex(row => row.team_id === team?.id) + 1, record = rank ? league.standings[rank - 1] : null;
  const club = <main className="newspaper club-page"><section className="club-paper"><button className="back-button" onClick={() => setView('teams')}>← VOLVER A EQUIPOS</button>{!team ? <div className="arcade-state">CARGANDO FICHA...</div> : <><header className="club-header"><TeamMark team={team} className="club-crest"/><div><p>{team.kind === 'national_team' ? 'SELECCIÓN' : 'CLUB'} · {team.currentDivision ?? 'LIGA DE TRANSICIÓN'}</p><h1>{team.name}</h1><span>PRESIDENTE: {team.president?.name ?? team.presidentName ?? 'SIN ASIGNAR'}</span></div><div className="club-rank"><small>LUGAR EN LA LIGA</small><b>{rank || '—'}°</b><strong>{record?.points ?? '—'} PTS</strong></div></header><div className="club-stats"><span>VALOR PLANTEL <b>{gp(team.squadValue)} GP</b></span><span>PROMEDIO <b>{gp(team.averageValue)} GP</b></span><span>JUGADORES <b>{team.playerCount ?? squad.length}</b></span><span>PARTIDOS <b>{record?.played ?? '—'}</b></span></div><div className="club-columns"><section className="club-info"><h2>PERFIL DEL CLUB</h2><dl><div><dt>PRESIDENTE</dt><dd>{team.president?.name ?? team.presidentName ?? 'Sin asignar'}</dd></div><div><dt>DIRECTOR TÉCNICO</dt><dd>{team.coach?.name ?? team.manager?.name ?? team.coachName ?? team.managerName ?? 'No informado'}</dd></div><div><dt>PRESUPUESTO</dt><dd>{team.budget ?? team.budgetValue ? `${gp(team.budget ?? team.budgetValue)} GP` : 'No informado'}</dd></div><div><dt>HISTORIA</dt><dd>{team.history ?? 'La historia pública aún no ha sido registrada por la liga.'}</dd></div></dl><h2>PALMARÉS</h2><p className="empty-copy">No hay títulos publicados para este equipo.</p></section><section className="roster-panel"><h2>PLANTEL TITULAR <small>{starters.length} / 11</small></h2><div className="roster-list">{starters.length ? starters.map(player) : <p className="empty-copy">No hay titulares definidos.</p>}</div><h2>SUPLENTES <small>{substitutes.length}</small></h2><div className="roster-list substitutes">{substitutes.length ? substitutes.map(player) : <p className="empty-copy">No hay suplentes registrados.</p>}</div></section></div></>}</section></main>;
  const matches = (rows, kind) => <section className="score-panel"><h2>{kind}</h2>{rows.length ? rows.map(match => <div className="score-line" key={match.id}><TeamMark team={resolve(match.homeTeam)}/><span className="home-name">{match.homeTeam.name}</span>{kind === 'ÚLTIMOS RESULTADOS' ? <strong>{match.homeScore} - {match.awayScore}</strong> : <span className="versus">VS</span>}<span className="away-name">{match.awayTeam.name}</span><TeamMark team={resolve(match.awayTeam)}/></div>) : <p className="league-note">{state.loading ? 'CARGANDO...' : 'SIN PARTIDOS PUBLICADOS.'}</p>}</section>;
  const sidebar = <aside className="match-sidebar">{matches(completed, 'ÚLTIMOS RESULTADOS')}<section className="score-panel upcoming-panel"><h2>PRÓXIMOS PARTIDOS <small>{upcoming[0]?.roundNumber ? `FECHA ${upcoming[0].roundNumber}` : ''}</small></h2>{upcoming.length ? upcoming.map(match => <div className="score-line" key={match.id}><TeamMark team={resolve(match.homeTeam)}/><span className="home-name">{match.homeTeam.name}</span><span className="versus">VS</span><span className="away-name">{match.awayTeam.name}</span><TeamMark team={resolve(match.awayTeam)}/></div>) : <p className="league-note">SIN PARTIDOS PENDIENTES.</p>}</section><section className="score-panel standings-panel"><h2>CLASIFICACIÓN</h2><table><thead><tr><th>#</th><th>EQUIPO</th><th>PJ</th><th>DG</th><th>PTS</th></tr></thead><tbody>{league.standings.slice(0, 5).map((row, index) => <tr key={row.team_id}><td>{index + 1}</td><td><TeamMark team={resolve(row)}/>{row.name}</td><td>{row.played}</td><td>{row.gd > 0 ? '+' : ''}{row.gd}</td><td>{row.points}</td></tr>)}</tbody></table>{!state.loading && !league.standings.length && <p className="league-note">SIN TABLA PUBLICADA.</p>}</section></aside>;
  return <div className="desktop-frame" style={{ width: 1536 * scale, height: 1024 * scale }}><div className="football-world" style={{ transform: `scale(${scale})` }}><header className="game-header"><p className="header-motto">JUEGA<br/>COMPITE<br/>CONECTA<br/>HISTORIA</p><div className="brand-ball"/><button className="brand" onClick={() => setView('home')}><span className="brand-top">KOINONIA</span><span className="brand-bottom">e-LEAGUE</span><span className="brand-caption">e F O O T B A L L&nbsp;&nbsp; T O U R N A M E N T S</span></button><div className="header-player"/><p className="header-promise">MÁS QUE<br/>UN JUEGO,<br/>UNA LIGA.</p><p className="header-community">CLUBES REALES<br/>AMIGOS VIRTUALES<br/>HISTORIAS ETERNAS</p></header><div className="home-composition">{nav}{view === 'home' ? home : view === 'teams' ? teams : club}{sidebar}</div><footer className="field-footer"><small>KOINONIA e-LEAGUE<br/>© 2026 · DATOS EN VIVO</small></footer>{state.error && <div className="preview-notice" role="status">{state.error}<button onClick={() => setState(current => ({ ...current, error: '' }))} aria-label="Cerrar aviso">×</button></div>}</div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
